version: '3.9'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: kv-hr-backend
    env_file:
      - local.env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - node-network
  postgres:
    container_name: postgres-kv-hr
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - node-network
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - node-network

    

networks:
  node-network:
    driver: bridge